image: Visual Studio 2019

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

build_script:
- cmd: dotnet build ./src/ComAdmin.sln -c Release

test_script: 
- cmd: dotnet test ./src/ComAdmin.sln

after_test:
- cmd: dotnet pack ./src/ComAdmin.sln -c Release

artifacts:
- path: './src/**/bin/Release/**/*.nupkg'
  name: NuGetPackages
  
# Deploy to GitHub and NuGet when we push a version tag.
deploy:
- provider: GitHub
  auth_token:
    secure: KTWUORrnJKPKLSf/3ROLY50T9UfgTMnKHf3OjBOv8tlY/DAxtlglRU3eM+j45fMt
  artifact: /.*(\.|\.s)nupkg/
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: TWio+nDN8Ew7+OH7J3tLcEoM6DmxrIwfAr+2Ag8ROWJUEnXyoSAZ/I1GxBgB0qMd
  artifact: /.*(\.|\.s)nupkg/
  on:
    APPVEYOR_REPO_TAG: true
